title: Kupeel Docs
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://kupeel.github.io/kupeel.github.io

aux_links:
  Template Repository: https://github.com/kupeel/kupeel.github.io
